<?php $this->headScript()->appendFile('/js/cra.js'); ?>


<?php

if (isset($this->aListeCra)):

?>

<table id="tableau">
    <caption>Choisir un mois d'activité</caption>
    <tbody>
<?php foreach ($this->aListeCra as $aMonth): ?>
        <tr>
            <td><a href="/cra/saisir/year/<?php echo $aMonth['year']; ?>/month/<?php echo $aMonth['month']; ?>"><?php echo $aMonth['date']?></a></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>
<!-- Idem, les données ne sont pas organisés de la bonne façon,
je ne peux pas boucler par projet pour chaque élément et créer le tableau correctement -->
<form name="cra" action="" method="POST">
<table id="tableau">
    <caption>Feuille de temps</caption>
    <thead>
        <tr>
            <th>Projets</th>
        
        <?php
       
        $index = 0;
        foreach ($this->allDays as $aDay) {
            $noWork = ($aDay['weekend'] == true || $aDay['publicHoliday'] == true);
            $isValidation = (isset($aDay['validation']) && $aDay['validation'] > 0);
            $idProjetDay = (isset($aDay['idCollaboration']) ? $aDay['idCollaboration'] : null); 
        } 

        $projets = $this->aProjets;
        for($k = 0; $k < count($projets); $k++) {
            $projet = $projets[$k];
            
            if(count($projets) == 0)
                $projet = ''; ?>

            <th><input type="text" name="projet[]" size="7" value="<?php echo $projet?>"></th>
        
        <?php }?>
        </tr>

    </thead>

    <tfoot>
    </tfoot> 

    <tbody>
    
    <?php
    $i = 0;

    foreach ($this->allDays as $aDay) { 
    ?>
    <tr>     
        
        <td>
            <input type="date" name="jour[]" size="7" value="<?php echo $this->escape($aDay['date']); ?>" readonly="readonly" />
        </td>

        <?php 
        $allData = $this->aData;
        $date = $aDay['date'];
        for($k = 0, $nb = count($projets); $k < $nb; $k++) {
            
            $projet = $projets[$k];
            $checkedAM = '';
            $checkedPM = '';
           
            for($l = 0, $number = count($allData[$projet]['lignes']); $l < $number; $l++) {
                if($allData[$projet]['lignes'][$l]['jour'] == $date && $projet == $allData[$projet]['lignes'][$l]['projet']) {

                    if($allData[$projet]['lignes'][$l]['AM'] == 1)
                        $checkedAM = 'checked';
                    
                    if($allData[$projet]['lignes'][$l]['PM'] == 1)
                        $checkedPM = 'checked';

                }
            }
            ?> 

        <td>
            AM
            <input type="checkbox" name="matin[<?php echo $i?>]"value="1" <?php echo (($isValidation) ? 'readonly="readonly" ' : ''); echo $checkedAM?>/>
            
            PM
            <input type="checkbox" name="apresMidi[<?php echo $i?>]"value="1" <?php echo (($isValidation) ? 'readonly="readonly" ' : ''); echo $checkedAM?>/>
        </td> 

        <?php }?>
        
    </tr>
        <?php 
        $i++;
    }?>  
    </tbody>
</table>

<p>
    <label for="commentaires">Avez-vous des  commentaires?</label><br />
    <textarea name="commentaires" id="commentaires"></textarea>
</p>

<input type="submit" value="Envoyer" name="send">
<input type="submit" value="Envoyer et Contrôler" name="control"
    onclick="return confirm('Vous ne pourrez plus modifier ce CRA après avoir demandé le contrôle de celui-ci. Voulez-vous continuer ?');">
    
<a href="#" onclick="addLigne(); return false;">Ajouter une ligne</a>
<a href="#" onclick="addCol(); return false;">Ajouter une colonne</a>
</form>

<a href="/cra/saisir/">Retour</a>

<?php endif; ?>