<?php $this->headScript()->appendFile('/js/cra.js'); ?>


<?php

if (isset($this->aListeCra)):

?>

<table id="tableau">
    <caption>Choisir un mois d'activité</caption>
    <tbody>
<?php foreach ($this->aListeCra as $aMonth): ?>
        <tr>
            <td><a href="/cra/saisir/year/<?php echo $aMonth['year']; ?>/month/<?php echo $aMonth['month']; ?>"><?php echo $aMonth['date']?></a></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>
<!-- Idem, les données ne sont pas organisés de la bonne façon,
je ne peux pas boucler par projet pour chaque élément et créer le tableau correctement -->
<form name="cra" action="" method="POST">
<table id="tableau">
    <caption>Feuille de temps</caption>
    <thead>
        <tr>
            <th>Projets</th>
            <?php
        $index = 0;
        foreach ($this->allDays as $aDay) {
            $noWork = ($aDay['weekend'] == true || $aDay['publicHoliday'] == true);
            $isValidation = (isset($aDay['validation']) && $aDay['validation'] > 0);
            $idProjetDay = (isset($aDay['idCollaboration']) ? $aDay['idCollaboration'] : null); 
        } 
        $projets = $this->aProjets;
        for($k = 0; $k < count($projets); $k++) {
            $projet = $projets[$k];
            if(count($projets) == 0){
                $projet = '';
            }        ?>
            <th><input type="text" name="projet[]" size="7" value="<?php echo $projet?>"></th>
        <?php } ?>
        </tr>
    </thead>
    <tfoot>
    </tfoot> 
    <tbody>
    <?php

    
    $allDate = $this->aDays;
    $i = 0;
    foreach ($this->allDays as $aDay) { 
    ?>
    <tr>     
        <td><input type="date" name="jour[]" size="7" value="<?php echo $this->escape($aDay['date']); ?>" readonly="readonly" /></td>
        <td>
            AM
            <input type="hidden" name="matin[<?php echo $i?>]" value="0" />
            <input type="checkbox" name="matin[<?php echo $i?>]"value="1" <?php echo (($isValidation) ? 'readonly="readonly" ' : ''); ?>/>
            
            PM
            <input type="hidden" name="apresMidi[<?php echo $i?>]" value="0" />
            <input type="checkbox" name="apresMidi[<?php echo $i?>]"value="1" <?php echo (($isValidation) ? 'readonly="readonly" ' : ''); ?>/>
        </td>
    </tr>
        <?php 
        $i++;
    }?>
        <!-- <tr id="ligne_<?php //echo $index++; ?>" class="<?php// echo $noWork ? 'noWorkLine' : ''; ?>">
            <td><input type="text" name="projet[]" size="7"?></td>
            <td><input type="date" name="jour[]" size="7" value="<?php //echo $this->escape($aDay['date']); ?>" readonly="readonly" /></td>
            <?php $iMatinDay //= (//isset($aDay['matin']) ? $aDay['matin'] / 60 : null); ?>
            <td><input type="checkbox" name="matin[]" <?php// echo ($iMatinDay !== null) ? 'value="1" ' : ''; echo (($isValidation) ? 'readonly="readonly" ' : ''); ?>/></td>
            <?php $iApremDay //= (//isset($aDay['apresMidi']) ? $aDay['apresMidi'] / 60 : null); ?>
            <td><input type="checkbox" name="apresMidi[]" <?php //echo ($iApremDay !== null) ? 'value="1" ' : ''; echo (($isValidation) ? 'readonly="readonly" ' : ''); ?>/></td>
            <td><input type="text" name="commentaires[]" size="7"?></td>
            <td><input type="hidden" name="validation[]" value="<?php //echo isset($aDay['validation']) ? $aDay['validation'] : '0';?>"/><a href="#" onclick="delLigne(this); return false;">Supprimer</a></td>
        </tr>
         -->
    </tbody>
</table>

<p>
    <label for="commentaires">Avez-vous des  commentaires?</label><br />
    <textarea name="commentaires" id="commentaires"></textarea>
</p>

<input type="submit" value="Envoyer" name="send">
<input type="submit" value="Envoyer et Contrôler" name="control"
    onclick="return confirm('Vous ne pourrez plus modifier ce CRA après avoir demandé le contrôle de celui-ci. Voulez-vous continuer ?');">
    
<a href="#" onclick="addLigne(); return false;">Ajouter une ligne</a>
<a href="#" onclick="addCol(); return false;">Ajouter une colonne</a>
</form>

<a href="/cra/saisir/">Retour</a>

<?php endif; ?>
