<?php if (empty($this->allCollaborateur)) : ?>
<p>Il n'existe aucun collaborateur.</p>
<?php else : ?>

<table>
    <form action="<?php echo $this->baseUrl ?>/collaborateur/modif" method="post">
	<caption>Collaborateur</caption>
    <thead>
        <tr>
            <th></th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Adresse</th>
            <th>Téléphone</th>
            <th>Mail</th>
            <th>Intitulé de Poste</th>
            <th>Compétences Fonctionnelles</th>
            <th>Compétences Techniques</th>
        </tr>
    </thead>
    <tfoot>
     <!-- //<tfoot> is optionnal but if you want it, you NEED to place it before <tbody> --> 

    </tfoot>
    <tbody>
    <?php 
    foreach($this->allCollaborateur as $collaborateur) {
        echo '<tr>';
        echo '<td><input type="radio" name="id" value="'.  $this->escape($collaborateur['id']) . '"/></td>';
        echo '<td>' . $this->escape($collaborateur['nom']) . '</td>';
        echo '<td>' . $this->escape($collaborateur['prenom']) . '</td>';
        echo '<td>' . $this->escape($collaborateur['adresse']) . '</td>';
        echo '<td>' . $this->escape($collaborateur['telephone']) . '</td>';
        echo '<td>' . $this->escape($collaborateur['mail']) . '</td>';
        echo '<td>' . $this->escape($collaborateur['intitule']) . '</td>';
        echo '<td>' . $this->escape($collaborateur['competencesf']) . '</td>';
        echo '<td>' . $this->escape($collaborateur['competencest']) . '</td>';
        echo '</tr>';
    }
    ?>
    </tbody>
</table>
    <p>
       <input class="submit" name="submit" type="submit" value="Submit">
    </p>
</form>

<?php endif; ?>