<table>
    <form action="<?php echo $this->baseUrl ?>/client/modif" method="post">
	<caption>Clients</caption>
    <thead>
        <tr>
            <th></th>
            <th>Nom</th>
            <th>Secteur</th>
            <th>Siège</th>
            <th>Contact Principal</th>
            <th>Téléphone (Principal)</th>
            <th>Mail (Principal)</th>
        </tr>
    </thead>
    <tfoot>
     <!-- //<tfoot> is optionnal but if you want it, you NEED to place it before <tbody> --> 

    </tfoot>
    <tbody>
    <?php 
    foreach($this->allClients as $client) {
        echo '<tr>';
        echo '<td><input type="radio" name="id" value="'.  $this->escape($client['id']) . '"/></td>';
        echo '<td>' . $this->escape($client['nom']) . '</td>';
        echo '<td>' . $this->escape($client['secteur']) . '</td>';
        echo '<td>' . $this->escape($client['siege']) . '</td>';
        echo '<td>' . $this->escape($client['contactp']) . '</td>';
        echo '<td>' . $this->escape($client['telp']) . '</td>';
        echo '<td>' . $this->escape($client['mailp']) . '</td>';
        echo '</tr>';
    }
    ?>
    </tbody>
    
</table>
<p>
    <input class="submit" name="submit" type="submit" value="Submit">
</p>
</form>
